BASE: ['']
TOOLBOX_MODE: "train_and_test"  # "train_and_test" or "only_train" or "only_test"
TRAIN:
  BATCH_SIZE: 4
  EPOCHS: 30
  LR: 1e-3
  MODEL_FILE_NAME: UBFC_UBFC_PURE_FactorizePhys_v10_R1_S1_ST4_TanH_NMF_MulRes
  PLOT_LOSSES_AND_LR: True
  DATA:
    FS: 30
    DATASET: UBFC-rPPG
    DO_PREPROCESS: False                    # if first time, should be true
    DATA_FORMAT: NCDHW
    DATA_PATH: "/mnt/sda/data/jitesh/UBFC-rPPG/data/"                     # Raw dataset path, need to be updated
    CACHED_PATH: "/home/jitesh/data/UBFC-rPPG/"    # Processed dataset save path, need to be updated
    EXP_DATA_NAME: "UBFC-rPPG_Raw_160_72x72"
    BEGIN: 0.0
    END: 0.8
    PREPROCESS:
      DATA_TYPE: ['Raw']
      DATA_AUG: ['None']    # 'None' or 'Motion' is supported, used if the data path points to an augmented dataset or requires augmentation
      LABEL_TYPE: Standardized
      DO_CHUNK: True
      CHUNK_LENGTH: 160
      CROP_FACE:
        DO_CROP_FACE: True
        BACKEND: 'Y5F'    # HC for Haar Cascade, RF for RetinaFace, Y5F for YOLO5Face
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: True
          DYNAMIC_DETECTION_FREQUENCY : 30
          USE_MEDIAN_FACE_BOX: False    # This should be used ONLY if dynamic detection is used
      RESIZE:
        H: 72
        W: 72
VALID:
  DATA:
    FS: 30
    DATASET: UBFC-rPPG
    DO_PREPROCESS: False                  # if first time, should be true
    DATA_FORMAT: NCDHW
    DATA_PATH: "/mnt/sda/data/jitesh/UBFC-rPPG/data/"                     # Raw dataset path, need to be updated
    CACHED_PATH: "/home/jitesh/data/UBFC-rPPG/"    # Processed dataset save path, need to be updated
    EXP_DATA_NAME: "UBFC-rPPG_Raw_160_72x72"
    BEGIN: 0.8
    END: 1.0
    PREPROCESS:
      DATA_TYPE: ['Raw']
      DATA_AUG: ['None']    # 'None' or 'Motion' is supported, used if the data path points to an augmented dataset or requires augmentation
      LABEL_TYPE: Standardized
      DO_CHUNK: True
      CHUNK_LENGTH: 160
      CROP_FACE:
        DO_CROP_FACE: True
        BACKEND: 'Y5F'    # HC for Haar Cascade, RF for RetinaFace, Y5F for YOLO5Face
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: True
          DYNAMIC_DETECTION_FREQUENCY : 30
          USE_MEDIAN_FACE_BOX: False    # This should be used ONLY if dynamic detection is used
      RESIZE:
        H: 72
        W: 72
TEST:
  METRICS: ['MAE', 'RMSE', 'MAPE', 'Pearson', 'SNR', 'BA', 'MACC']
  USE_LAST_EPOCH: False                   # to use provided validation dataset to find the best epoch, should be false
  DATA:
    FS: 30
    DATASET: PURE
    DO_PREPROCESS: False            # if first time, should be true
    DATA_FORMAT: NCDHW
    DATA_PATH: "/mnt/sda/data/jitesh/PURE_Dataset/raw"                     # Raw dataset path, need to be updated
    CACHED_PATH: "/home/jitesh/data/PURE_Dataset"    # Processed dataset save path, need to be updated
    EXP_DATA_NAME: "PURE_Raw_160_72x72"
    BEGIN: 0.0
    END: 1.0
    PREPROCESS:
      DATA_TYPE: ['Raw']
      LABEL_TYPE: Standardized
      DO_CHUNK: True
      CHUNK_LENGTH: 160
      CROP_FACE:
        DO_CROP_FACE: True
        BACKEND: 'Y5F'    # HC for Haar Cascade, RF for RetinaFace, Y5F for YOLO5Face
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: True
          DYNAMIC_DETECTION_FREQUENCY : 30
          USE_MEDIAN_FACE_BOX: False    # This should be used ONLY if dynamic detection is used
      RESIZE:
        H: 72
        W: 72
DEVICE: cuda:0
NUM_OF_GPU_TRAIN: 1
LOG:
  PATH: runs/exp
MODEL:
  DROP_RATE: 0.1
  NAME: FactorizePhys
  FactorizePhys:
    CHANNELS: 3
    FRAME_NUM: 160
    MD_FSAM: True
    MD_TYPE: "NMF"
    MD_R: 1
    MD_S: 1
    MD_STEPS: 4
INFERENCE:
  BATCH_SIZE: 4
  EVALUATION_METHOD: "FFT"        # "FFT" or "peak detection"
  EVALUATION_WINDOW:
    USE_SMALLER_WINDOW: False        # Change this if you'd like an evaluation window smaller than the test video length
    WINDOW_SIZE: 30        # In seconds
  MODEL_PATH: "./runs/exp/UBFC-rPPG_Raw_160_72x72/PreTrainedModels/UBFC_UBFC_PURE_FactorizePhys_v01_R1_S1_ST6_ELU_B_Mul_OnesInit_Epoch29.pth"
  # MODEL_PATH: "./runs/exp/UBFC-rPPG_Raw_160_72x72/PreTrainedModels/UBFC_UBFC_PURE_FactorizePhys_v01_R1_S4_ST6_ELU_BN_MulRes_Epoch29.pth"
  # MODEL_PATH: "./runs/exp/UBFC-rPPG_Raw_160_72x72/PreTrainedModels/UBFC_UBFC_PURE_FactorizePhys_v63_R4_S8_ST6_Mul_II_LR5e-4_Epoch29.pth"
  # MODEL_PATH: "./runs/exp/UBFC-rPPG_Raw_160_72x72/PreTrainedModels/UBFC_UBFC_PURE_FactorizePhys_v63_R4_S4_ST5_Mul_II_OnesInit_Grad_Epoch29.pth"
  # MODEL_PATH : "./runs/exp/UBFC-rPPG_Raw_160_72x72/PreTrainedModels/UBFC_UBFC_PURE_FactorizePhys_v63_R4_S4_ST4_LR1e-3_Mul_InstanceNorm_Epoch29.pth"
  # MODEL_PATH: "./runs/exp/UBFC-rPPG_Raw_160_72x72/PreTrainedModels/UBFC_UBFC_PURE_FactorizePhys_v63_R1_S10_ST4_LR1e-3_Res_Epoch4.pth"
  # MODEL_PATH: "./runs/exp/UBFC-rPPG_Raw_160_72x72/PreTrainedModels/UBFC_UBFC_PURE_FactorizePhys_v63_R1_S2_ST4_LR1e-3_Res_Epoch29.pth"
  # MODEL_PATH: "./runs/exp/UBFC-rPPG_Raw_160_72x72/PreTrainedModels/UBFC_UBFC_PURE_FactorizePhys_v63_R1_S16_ST6_LR1e-3_Res_Epoch29.pth"
  # MODEL_PATH: "./runs/exp/UBFC-rPPG_Raw_160_72x72/PreTrainedModels/UBFC_UBFC_PURE_FactorizePhys_v63_R10_S8_ST6_LR1e-3_NoRes_Epoch29.pth"
  # MODEL_PATH: "./runs/exp/UBFC-rPPG_Raw_160_72x72/PreTrainedModels/UBFC_UBFC_PURE_FactorizePhys_v63_R1_S16_ST6_LR1e-3_Res_Epoch29.pth"
  # MODEL_PATH: "./runs/exp/UBFC-rPPG_Raw_160_72x72/PreTrainedModels/UBFC_UBFC_PURE_FactorizePhys_v48_R5_S8_ST5_LR1e-3_Epoch29.pth"
  # MODEL_PATH: "./runs/exp/UBFC-rPPG_Raw_160_72x72/PreTrainedModels/UBFC_UBFC_PURE_FactorizePhys_v43_R1_S4_ST1_LR1e-4_Epoch11.pth"